title: Books Note
description: Catatan hasil membaca beberapa buku
theme: just-the-docs

url: https://ruswan.github.io/try-just-the-docs

aux_links:
  Template Repository: https://github.com/ruswan/try-just-the-docs
